### ISSUE TITLE
test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException doesn't instantiate duplicated twitter Jessy Borcard

### ISSUE THREAD

**Issue by tristepin222** [tristepin222/GPR1-SocialNetwork#1]
test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException only instantiate one instance of twitter with 15 followers
but the test says that it should be duplicated

The setup does make a new instantiation of twitter but it's empty, then the test make a new one with followers, but it's not duplicated, thus i think the test should not except an exception of type SubscriberAlreadyExistsException

impacted commit : [commit](https://github.com/tristepin222/GPR1-SocialNetwork/commit/c025ed42e7270177ecbb4793c4d6dd53f913bb1c)

aside that, everything else is passing without problems
-Jessy Borcard

**Comment by NicolasGlassey** [comment]
@tristepin222 

Hi Jessy,

I have taken your outcome into account for your assessment.

(as well as the correct commit reference)

Have a good weekend !
